var a = 5, b = 10, c = "5";
var x = a;
console.log(a === c);
console.log(a == c);
console.log(a == x);
console.log(a != b);
console.log(a > b);
console.log(a < b);
console.log(a >= b);
console.log(a <= b);
console.log(a >= c);
console.log(a <= c);